version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
phases:
  install:
    commands:
      - echo Installing Terraform and jq...
      - curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
      - unzip -q terraform.zip -d /usr/local/bin
      - terraform -version
      - yum install -y jq >/dev/null 2>&1 || true
  build:
    commands:
      - echo Applying Terraform...
      - set -e
      - echo "Looking for images.json among input artifacts..."
      - IMAGE_JSON=""
      - if [ -f "$CODEBUILD_SRC_DIR/images.json" ]; then IMAGE_JSON="$CODEBUILD_SRC_DIR/images.json"; fi
      - if [ -z "$IMAGE_JSON" ]; then
          env | sort | while IFS='=' read -r NAME VAL; do
            case "$NAME" in CODEBUILD_SRC_DIR_*) if [ -f "$VAL/images.json" ]; then echo "$VAL/images.json"; break; fi;; esac;
          done > /tmp/image_json_path;
          if [ -s /tmp/image_json_path ]; then IMAGE_JSON=$(cat /tmp/image_json_path); fi;
        fi
      - if [ -z "$IMAGE_JSON" ]; then echo "images.json not found in any input artifact"; env | sort | grep CODEBUILD_SRC_DIR || true; exit 1; fi
      - echo "Using images.json at $IMAGE_JSON"
      - IMAGE_TAGS=$(cat "$IMAGE_JSON")
      - TGR_TAG=$(echo $IMAGE_TAGS | jq -r '.textract_get_results')
      - terraform -chdir=terraform init -input=false
      - terraform -chdir=terraform apply -auto-approve -input=false -var="textract_get_results_tag=$TGR_TAG"
artifacts:
  files:
    - images.json
