version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
phases:
  install:
    commands:
      - echo Installing Terraform and jq...
      - curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
      - unzip -q terraform.zip -d /usr/local/bin
      - terraform -version
      - yum install -y jq >/dev/null 2>&1 || true
  build:
    commands:
      - echo Preparing Terraform plan...
      - set -e
      - echo "Looking for images.json among input artifacts..."
      - IMAGE_JSON=""
      - for d in "$CODEBUILD_SRC_DIR" ${CODEBUILD_SRC_DIR_*}; do if [ -n "$d" ] && [ -f "$d/images.json" ]; then IMAGE_JSON="$d/images.json"; break; fi; done; if [ -z "$IMAGE_JSON" ]; then echo "images.json not found in any input artifact"; env | sort | grep CODEBUILD_SRC_DIR || true; exit 1; fi
      - echo "Using images.json at $IMAGE_JSON"
      - IMAGE_TAGS=$(cat "$IMAGE_JSON")
      - cd terraform
      - ELC_TAG=$(echo $IMAGE_TAGS | jq -r '.extract_legal_claims')
      - GI_TAG=$(echo $IMAGE_TAGS | jq -r '.generate_instructions')
      - TGR_TAG=$(echo $IMAGE_TAGS | jq -r '.textract_get_results')
      - terraform init -input=false
      - terraform plan -out=tfplan -input=false \
          -var="extract_legal_claims_tag=$ELC_TAG" \
          -var="generate_instructions_tag=$GI_TAG" \
          -var="textract_get_results_tag=$TGR_TAG"
artifacts:
  files:
    - terraform/tfplan
    - images.json
